/**
 * Deterministic fictional records for the disconnected WhatsApp preview.
 * These do not represent real customers, phone numbers, campaigns, or portal
 * data. Keep this module free of fetches, environment variables, and secrets.
 */
export const WHATSAPP_FIXTURES = [
  {
    id: "wa-preview-northstar",
    contact: {
      name: "Riya Demo",
      company: "Northstar Demo Infra",
      externalId: "preview-contact-101",
      phone: "+91 00000 01001",
      location: "Demo City",
    },
    lastMessage: "Please share the roller specification sheet.",
    lastActivityAt: "2026-08-17T08:42:00+05:30",
    attentionState: "handover",
    leadCategory: "hot",
    classification: "interested",
    campaign: "Monsoon equipment preview",
    summary:
      "Fictional contractor evaluating walk-behind rollers for a road repair project. The contact requested technical specifications after reading the introductory template.",
    nextAction: "Review the requested specification and prepare a formal quotation.",
    products: ["Walk-behind roller"],
    requirements: "Compaction equipment for a fictional road repair project",
    budget: "Not captured",
    timeline: "This month",
    source: "Preview campaign",
    messages: [
      {
        id: "wa-n-1",
        direction: "operator",
        kind: "template",
        text: "Hello {{1}}, we have new compaction equipment options available for your project.",
        createdAt: "2026-08-16T11:15:00+05:30",
        status: "read",
        template: {
          name: "equipment_introduction_demo",
          language: "en",
          variables: ["Riya"],
        },
      },
      {
        id: "wa-n-2",
        direction: "customer",
        kind: "text",
        text: "Hi, I need a walk-behind roller for a road repair project.",
        createdAt: "2026-08-16T11:21:00+05:30",
        replyTo: {
          id: "wa-n-1",
          sender: "Divine Empire",
          text: "We have new compaction equipment options available.",
        },
      },
      {
        id: "wa-n-3",
        direction: "operator",
        kind: "document",
        text: "Here is a preview specification document.",
        createdAt: "2026-08-17T08:35:00+05:30",
        status: "delivered",
        media: {
          name: "roller-specification-preview.pdf",
          mimeType: "application/pdf",
          caption: "Walk-behind roller specification",
        },
      },
      {
        id: "wa-n-4",
        direction: "customer",
        kind: "text",
        text: "Please share the roller specification sheet.",
        createdAt: "2026-08-17T08:42:00+05:30",
      },
    ],
  },
  {
    id: "wa-preview-summit",
    contact: {
      name: "Arun Sample",
      company: "Summit Sample Projects",
      externalId: "preview-contact-102",
      phone: "+91 00000 01002",
      location: "Sample Nagar",
    },
    lastMessage: "Yes, show me the 32 mm model.",
    lastActivityAt: "2026-08-17T08:10:00+05:30",
    attentionState: "none",
    leadCategory: "warm",
    classification: "interested",
    campaign: "Rebar equipment preview",
    summary:
      "Fictional buyer responded to an interactive product selector and chose the 32 mm bar-bending machine option.",
    nextAction: "Confirm expected daily output and quantity before preparing options.",
    products: ["Bar bending machine — 32 mm"],
    requirements: "Interactive selection response",
    timeline: "Next quarter",
    source: "Interactive preview",
    messages: [
      {
        id: "wa-s-1",
        direction: "operator",
        kind: "interactive",
        text: "Which bar-bending capacity would you like to explore?",
        createdAt: "2026-08-17T08:03:00+05:30",
        status: "read",
        actions: ["25 mm", "32 mm", "40 mm"],
      },
      {
        id: "wa-s-2",
        direction: "customer",
        kind: "interactive",
        text: "Yes, show me the 32 mm model.",
        createdAt: "2026-08-17T08:10:00+05:30",
      },
    ],
  },
  {
    id: "wa-preview-blueprint",
    contact: {
      name: "Meera Example",
      company: "Blueprint Example Labs",
      externalId: "preview-contact-103",
      phone: "+91 00000 01003",
      location: "Example Pur",
    },
    lastMessage: "site-layout-preview.jpg",
    lastActivityAt: "2026-08-16T17:25:00+05:30",
    attentionState: "none",
    leadCategory: "warm",
    classification: "new",
    campaign: "Inbound preview",
    summary:
      "Fictional new enquiry containing an image of a site layout and a request for surveying equipment guidance.",
    nextAction: "Ask about accuracy requirements and project area.",
    products: ["Total station"],
    requirements: "Surveying recommendation based on a fictional site plan",
    source: "Inbound preview",
    messages: [
      {
        id: "wa-b-1",
        direction: "customer",
        kind: "text",
        text: "Which total station would suit this sample site?",
        createdAt: "2026-08-16T17:22:00+05:30",
      },
      {
        id: "wa-b-2",
        direction: "customer",
        kind: "image",
        text: "Fictional site layout for the UI preview.",
        createdAt: "2026-08-16T17:25:00+05:30",
        media: {
          name: "site-layout-preview.jpg",
          mimeType: "image/jpeg",
          caption: "Sample site layout",
        },
      },
    ],
  },
  {
    id: "wa-preview-failed",
    contact: {
      name: "Dev Preview",
      company: "Harbor Preview Works",
      externalId: "preview-contact-104",
      phone: "+91 00000 01004",
      location: "Preview Port",
    },
    lastMessage: "Template delivery failed",
    lastActivityAt: "2026-08-16T15:30:00+05:30",
    attentionState: "urgent",
    leadCategory: "cold",
    classification: "new",
    campaign: "Service reminder preview",
    summary:
      "Fictional contact included to demonstrate a failed outbound template and its visible error state.",
    nextAction: "Verify contact consent and number validity before retrying in a connected system.",
    products: [],
    source: "Delivery-status preview",
    messages: [
      {
        id: "wa-f-1",
        direction: "operator",
        kind: "template",
        text: "Your requested equipment information is ready.",
        createdAt: "2026-08-16T15:30:00+05:30",
        status: "failed",
        error: "Preview failure: recipient unavailable",
        template: {
          name: "information_ready_demo",
          language: "en",
          variables: [],
        },
      },
    ],
  },
  {
    id: "wa-preview-declined",
    contact: {
      name: "Kabir Fiction",
      company: "Cedar Fiction Trading",
      externalId: "preview-contact-105",
      phone: "+91 00000 01005",
      location: "Fiction Town",
    },
    lastMessage: "Not interested at the moment, thank you.",
    lastActivityAt: "2026-08-15T12:05:00+05:30",
    attentionState: "none",
    leadCategory: "not_interested",
    classification: "not_interested",
    campaign: "Catalog preview",
    summary: "Fictional contact declined further product information.",
    nextAction: "No follow-up. Respect the fictional contact preference.",
    products: [],
    source: "Classification preview",
    messages: [
      {
        id: "wa-d-1",
        direction: "operator",
        kind: "template",
        text: "Would you like to receive our latest equipment catalog?",
        createdAt: "2026-08-15T12:00:00+05:30",
        status: "read",
        template: {
          name: "catalog_offer_demo",
          language: "en",
          variables: [],
        },
      },
      {
        id: "wa-d-2",
        direction: "customer",
        kind: "text",
        text: "Not interested at the moment, thank you.",
        createdAt: "2026-08-15T12:05:00+05:30",
      },
    ],
  },
] as const;
